const ACADEMIC_PERIODS = {
  PRIMARY: ["TERM_1", "TERM_2", "TERM_3", "TERM_4"],
  SECONDARY: ["TERM_1", "TERM_2", "TERM_3", "TERM_4"],
  COLLEGE: ["SEMESTER_1", "SEMESTER_2"],
  VOCATIONAL: ["SEMESTER_1", "SEMESTER_2"],
};

module.exports = ACADEMIC_PERIODS;