const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  SCHOOL_ADMIN: "SCHOOL_ADMIN",
  PRINCIPAL: "PRINCIPAL",
  DEPUTY_PRINCIPAL: "DEPUTY_PRINCIPAL",
  BURSAR: "BURSAR",
  TEACHER: "TEACHER",
  HOD: "HOD",
  CLASS_TEACHER: "CLASS_TEACHER",
  STUDENT: "STUDENT",
  PARENT: "PARENT",
};

module.exports = ROLES;